name: Commitlint

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional

      - name: Create commitlint config
        run: |
          cat > commitlint.config.js << 'EOF'
          module.exports = {
            extends: ['@commitlint/config-conventional'],
            rules: {
              'type-enum': [
                2,
                'always',
                [
                  'feat',     // New feature
                  'fix',      // Bug fix
                  'docs',     // Documentation changes
                  'style',    // Code style changes (formatting, etc.)
                  'refactor', // Code refactoring
                  'perf',     // Performance improvements
                  'test',     // Adding or updating tests
                  'chore',    // Maintenance tasks
                  'ci',       // CI/CD changes
                  'build',    // Build system changes
                  'revert'    // Revert previous commit
                ]
              ],
              'type-case': [2, 'always', 'lower-case'],
              'type-empty': [2, 'never'],
              'scope-case': [2, 'always', 'lower-case'],
              'subject-case': [2, 'always', 'sentence-case'],
              'subject-empty': [2, 'never'],
              'subject-full-stop': [2, 'never', '.'],
              'header-max-length': [2, 'always', 72],
              'body-leading-blank': [1, 'always'],
              'body-max-line-length': [2, 'always', 100],
              'footer-leading-blank': [1, 'always'],
              'footer-max-line-length': [2, 'always', 100]
            }
          };
          EOF

      - name: Validate current commit (last commit)
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose 