#!/bin/bash

echo "GitHub Push Helper Script"
echo "========================"
echo ""
echo "This script will help you push the hoistscout code to GitHub."
echo ""

# Check if we're in the right directory
if [ ! -f "render.yaml" ]; then
    echo "Error: Not in hoistscout directory!"
    echo "Please run: cd /root/hoistscout"
    exit 1
fi

echo "Current git status:"
git status --short

echo ""
echo "To push to GitHub, you have two options:"
echo ""
echo "Option 1: Using HTTPS (recommended)"
echo "-----------------------------------"
echo "1. Run this command:"
echo "   git remote set-url origin https://github.com/jakelindsay87/hoistscout.git"
echo ""
echo "2. Then push:"
echo "   git push -u origin master"
echo ""
echo "3. Enter your GitHub username: jakelindsay87"
echo "4. Enter your GitHub password or Personal Access Token"
echo "   (If you have 2FA enabled, you must use a Personal Access Token)"
echo ""
echo "To create a Personal Access Token:"
echo "- Go to: https://github.com/settings/tokens"
echo "- Click 'Generate new token (classic)'"
echo "- Give it 'repo' permissions"
echo "- Copy the token and use it as your password"
echo ""
echo "Option 2: Using GitHub CLI"
echo "--------------------------"
echo "1. Login to GitHub CLI:"
echo "   gh auth login"
echo ""
echo "2. Then push:"
echo "   git push -u origin master"
echo ""
echo "Option 3: Using SSH (if you have SSH keys set up)"
echo "-------------------------------------------------"
echo "1. Add your SSH key to GitHub:"
echo "   https://github.com/settings/keys"
echo ""
echo "2. Then push:"
echo "   git push -u origin master"
echo ""
echo "After pushing, the repository will be available at:"
echo "https://github.com/jakelindsay87/hoistscout"
echo ""
echo "Then Render will be able to access it and deploy successfully!"