services:
  # Backend API Service
  - type: web
    name: hoistscraper-api
    runtime: docker
    repo: https://github.com/jakelindsay87/hoistscraper
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: CRAWL_CONCURRENCY
        value: "8"
      - key: DATABASE_URL
        sync: false # Set this in Render dashboard
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_USER
        sync: false # Set this in Render dashboard
      - key: SMTP_PASSWORD
        sync: false # Set this in Render dashboard
      - key: NOTIFY_EMAIL
        sync: false # Set this in Render dashboard
      - key: ANALYZE_TERMS
        value: "false"
    healthCheckPath: /health
    
  # Frontend Service
  - type: web
    name: hoistscraper-fe
    runtime: docker
    repo: https://github.com/jakelindsay87/hoistscraper
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://hoistscraper-api.onrender.com
      - key: NODE_ENV
        value: production

# Databases
databases:
  - name: hoistscraper-db
    databaseName: hoistscraper
    user: hoistscraper_user
    plan: free 