global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hoistscraper'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules files
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Scrape the backend API metrics
  - job_name: 'hoistscraper-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Scrape Node Exporter if deployed
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']