- name: Example
  start_urls: ["https://foo.bar/grants"]
  pagination:
    selector: "a[rel=next]"
    limit: 10
  auth:
    type: login_form
    username_env: EX_USER
    password_env: EX_PASS
    login_url: https://foo.bar/login
    selectors:
      user: "#u"
      pass: "#p"
      submit: "button[type=submit]"
  selectors:
    grants: ".grant-item"
    titles: ".grant-title"
    descriptions: ".grant-description"
  delay: 2.0
  timeout: 30 