name: CI
on: [push, pull_request]

jobs:
  integration-tests:
    name: Integration Tests (with Database)
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hoistscraper_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          cd backend
          poetry install --with dev
      
      - name: Run integration tests (with database)
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/hoistscraper_test
        run: |
          cd backend
          poetry run pytest -m integration -v --cov=hoistscraper --cov-report=term-missing

  unit-tests:
    name: Unit Tests and Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          cd backend
          poetry install --with dev
      
      - name: Install Playwright
        run: |
          cd backend
          poetry run playwright install --with-deps
      
      - name: Run Python linting
        run: |
          cd backend
          poetry run ruff check
      
      - name: Run Python unit tests
        run: |
          cd backend
          poetry run pytest -m "not integration" -v

  test-fe:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Run linting
        run: |
          cd frontend
          npm run lint
      
      - name: Run type checking
        run: |
          cd frontend
          npm run type-check
      
      - name: Run tests
        run: |
          cd frontend
          npm run test
      
      - name: Verify Next.js build
        env:
          NODE_OPTIONS: "--max-old-space-size=2048"
        run: |
          cd frontend
          npm run build

  test-queue:
    name: Queue and Worker Tests
    runs-on: ubuntu-latest
    needs: [integration-tests, unit-tests, test-fe]
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          cd backend
          poetry install --with dev
      
      - name: Run queue and worker tests
        run: |
          cd backend
          poetry run pytest tests/test_queue.py tests/test_worker.py -v --cov=hoistscraper.queue --cov=hoistscraper.worker --cov-report=term-missing 